---
- hosts: 192.168.60.20
  roles:
  - role: dorzhevsky.docker
  - role: dorzhevsky.weave
  tasks:
  - include: mysql.yaml


- hosts: 192.168.60.30
  roles:
  - role: dorzhevsky.docker
  - role: dorzhevsky.weave
    peer_ip: 192.168.60.20
  tasks:
  - include: mysql.yaml
