---
#- hosts: 192.168.60.10
#  tasks:
#  - name: Copy docker repository key
#    copy:
#      src: ./docker.gpg.key
#      dest: /opt/docker.gpg.key
#    become: true
#  - name: Install docker repository key
#    apt_key:
#      file: /opt/docker.gpg.key
#      state: present
#      validate_certs: no
#    become: true
#  - name: Add docker repository
#    apt_repository:
#      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable
#      state: present
#    become: true
#  - name: Install docker ce
#    apt:
#      name: docker-ce
#      state: present
#      update_cache: yes
#    become: true
#  - name: Add docker group
#    group:
#      name: docker
#      state: present
#    become: true
#  - name: Add user to docker group
#    user:
#      name: vagrant
#      groups: docker
#      append: yes
#    become: true
#  - name: Install pip
#    apt:
#      name: python-pip
#      state: present
#    become: true
#  - name: Install docker-py
#    pip:
#      name: docker-py
#      state: present
#      version: 1.9.0
#    become: true
#  - name: Pull etcd image
#    docker_image:
#      name: quay.io/coreos/etcd
#      tag: v2.3.0-alpha.1
#      state: present
#    become: true
#  - name: Create etcd container
#    docker_container:
#      name: etcd
#      image: quay.io/coreos/etcd:v2.3.0-alpha.1
#      state: present
#      network_mode: host
#      command: -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -advertise-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
#    become: true
#  - name: Start etcd container
#    docker_container:
#      name: etcd
#      state: started
#    become: true
#  - name: Pull skydns image
#    docker_image:
#      name: yaronr/skydns
#      state: present
#    become: true
#  - name: Create skydns container
#    docker_container:
#      name: skydns
#      image: yaronr/skydns
#      state: present
#      network_mode: host
#      env:
#        ETCD_MACHINES: http://192.168.60.10:4001
#    become: true
#  - name: Create skydns config key
#    uri: 
#      url: "http://localhost:4001/v2/keys/skydns/config"
#      method: PUT
#      body: "value={\"dns_addr\": \"0.0.0.0:53\", \"domain\": \"services.local\", \"nameservers\": [\"8.8.8.8:53\"], \"ttl\": 30 }"
#      status_code: 200,201
#  - name: Start skydns container
#    docker_container:
#      name: skydns
#      state: started
#    become: true


- hosts: 192.168.60.20
  roles:
  - dorzhevsky.docker
  - role: dorzhevsky.weave
#  tasks:
#  - name: Pull registrator image
#    docker_image:
#      name: gliderlabs/registrator
#      state: present
#    become: true
#  - name: Create registrator container
#    docker_container:
#      name: registrator
#      image: gliderlabs/registrator
#      state: present
#      network_mode: host
#      volumes:
#        - /var/run/docker.sock:/tmp/docker.sock
#      command: --internal skydns2://192.168.60.10:4001/services.local
#    become: true
#  - name: Start registrator container
#    docker_container:
#      name: registrator
#      state: started
#    become: true


- hosts: 192.168.60.30
  roles:
  - dorzhevsky.docker
  - role: dorzhevsky.weave
    peer_ip: 192.168.60.20
    
#  - name: Pull registrator image
#    docker_image:
#      name: gliderlabs/registrator
#      state: present
#    become: true
#  - name: Create registrator container
#    docker_container:
#      name: registrator
#      image: gliderlabs/registrator
#      state: present
#      network_mode: host
#      volumes:
#        - /var/run/docker.sock:/tmp/docker.sock
#      command: --internal skydns2://192.168.60.10:4001/services.local
#    become: true
#  - name: Start registrator container
#    docker_container:
#      name: registrator
#      state: started
#    become: true
